workdir: work
genome: /home/fforge/Stage-IA3D/notebooks/resources/genome/Homo_sapiens.GRCh38.dna.primary_assembly/sequence.fa
experiments: /home/fforge/Stage-IA3D/orca_snake/lil.tsv
region: chr9:1-32000000
muttype: shuffle
nb_random: 10
resol_model: 32Mb
mpos: 15_872_000
no_cuda: True
score_types: insulation_count,PC1
merged_by: rdm
resol: None
show_rdm: False
