workdir: work
genome: /work/user/fforge/work/resources/genome/Homo_sapiens.GRCh38.dna.primary_assembly/sequence.fa
experiments: /work/user/fforge/work/orca_snake/lil_rdm_bed.tsv
region: chr9:1-32000000
muttype: insertion
nb_random: 10
rdm_seq: True
resol_model: 32Mb
mpos: 15_872_000
no_cuda: True
score_types: insulation_count,PC1
merged_by: rdm
resol: None
show_rdm: False
